src/blog/urls.py
"""URL paths for Blog App"""
from django.urls import path

from .views import (
    PostArchiveMonth,
    PostArchiveYear,
    PostCreate,
    PostDelete,
    PostDetail,
    PostList,
    PostUpdate,
)

urlpatterns = [
    path("", PostList.as_view(), name="post_list"),
    path(
        "create/", PostCreate.as_view(), name="post_create"
    ),
    path(
        "<int:year>/",
        PostArchiveYear.as_view(),
        name="post_archive_year",
    ),
    path(
        "<int:year>/<int:month>/",
        PostArchiveMonth.as_view(),
        name="post_archive_month",
    ),
    path(
        "<int:year>/<int:month>/<str:slug>/",
        PostDetail.as_view(),
        name="post_detail",
    ),
    path(
        "<int:year>/<int:month>/<str:slug>/delete/",
        PostDelete.as_view(),
        name="post_delete",
    ),
    path(
        "<int:year>/<int:month>/<str:slug>/update/",
        PostUpdate.as_view(),
        name="post_update",
    ),
]

src/organizer/models.py
"""Django data models for organizing startup company data

Django Model Documentation:
https://docs.djangoproject.com/en/2.2/topics/db/models/
https://docs.djangoproject.com/en/2.2/ref/models/options/
https://docs.djangoproject.com/en/2.2/internals/contributing/writing-code/coding-style/#model-style
Django Field Reference:
https://docs.djangoproject.com/en/2.2/ref/models/fields/
https://docs.djangoproject.com/en/2.2/ref/models/fields/#charfield
https://docs.djangoproject.com/en/2.2/ref/models/fields/#datefield
https://docs.djangoproject.com/en/2.2/ref/models/fields/#emailfield
https://docs.djangoproject.com/en/2.2/ref/models/fields/#foreignkey
https://docs.djangoproject.com/en/2.2/ref/models/fields/#manytomanyfield
https://docs.djangoproject.com/en/2.2/ref/models/fields/#slugfield
https://docs.djangoproject.com/en/2.2/ref/models/fields/#textfield
https://docs.djangoproject.com/en/2.2/ref/models/fields/#urlfield

AutoSlugField Reference:
https://django-extensions.readthedocs.io/en/latest/field_extensions.html

"""
from django.db.models import (
    CASCADE,
    CharField,
    DateField,
    EmailField,
    FileField,
    ForeignKey,
    ManyToManyField,
    Model,
    SlugField,
    TextField,
    URLField,
)
from django.urls import reverse
from django_extensions.db.fields import AutoSlugField


class Tag(Model):
    """Labels to help categorize data"""

    name = CharField(max_length=31, unique=True)
    slug = AutoSlugField(
        help_text="A label for URL config.",
        max_length=31,
        populate_from=["name"],
    )

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """Return URL to detail page of Tag"""
        return reverse(
            "tag_detail", kwargs={"slug": self.slug}
        )

    def get_update_url(self):
        """Return URL to update page of Tag"""
        return reverse(
            "tag_update", kwargs={"slug": self.slug}
        )

    def get_delete_url(self):
        """Return URL to delete page of Tag"""
        return reverse(
            "tag_delete", kwargs={"slug": self.slug}
        )


class Startup(Model):
    """Data about a Startup company"""

    name = CharField(max_length=31, db_index=True)
    slug = SlugField(
        max_length=31,
        unique=True,
        help_text="A label for URL config.",
    )
    # https://docs.djangoproject.com/en/2.2/ref/models/fields/#filefield
    logo = FileField(null=True)
    description = TextField()
    founded_date = DateField("date founded")
    contact = EmailField()
    website = URLField(
        max_length=255  # https://tools.ietf.org/html/rfc3986
    )
    tags = ManyToManyField(Tag)

    class Meta:
        get_latest_by = "founded_date"
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """Return URL to detail page of Startup"""
        return reverse(
            "startup_detail", kwargs={"slug": self.slug}
        )

    def get_update_url(self):
        """Return URL to update page of Startup"""
        return reverse(
            "startup_update", kwargs={"slug": self.slug}
        )

    def get_delete_url(self):
        """Return URL to delete page of Startup"""
        return reverse(
            "startup_delete", kwargs={"slug": self.slug}
        )

    def get_newslink_create_url(self):
        """Return URL to detail page of Startup"""
        return reverse(
            "newslink_create",
            kwargs={"startup_slug": self.slug},
        )


class NewsLink(Model):
    """Link to external sources about a Startup"""

    title = CharField(max_length=63)
    slug = SlugField(max_length=63)
    pub_date = DateField("date published")
    link = URLField(
        max_length=255  # https://tools.ietf.org/html/rfc3986
    )
    startup = ForeignKey(Startup, on_delete=CASCADE)

    class Meta:
        get_latest_by = "pub_date"
        ordering = ["-pub_date"]
        unique_together = ("slug", "startup")
        verbose_name = "news article"

    def __str__(self):
        return f"{self.startup}: {self.title}"

    def get_absolute_url(self):
        """Return URL to detail page of Startup"""
        return reverse(
            "startup_detail",
            kwargs={"slug": self.startup.slug},
        )

    def get_update_url(self):
        """Return URL to update page of Startup"""
        return reverse(
            "newslink_update",
            kwargs={
                "startup_slug": self.startup.slug,
                "newslink_slug": self.slug,
            },
        )

    def get_delete_url(self):
        """Return URL to delete page of Startup"""
        return reverse(
            "newslink_delete",
            kwargs={
                "startup_slug": self.startup.slug,
                "newslink_slug": self.slug,
            },
        )

src/templates/startup/confirm_delete.html
{% extends parent_template|default:"startup/base.html" %}

{% block title %}
  {{ startup.name }}: delete?
{% endblock %}

{% block content %}
  <form
      action="."
      method="post"
  >
    {% csrf_token %}
    <p>
      Are you sure you want to delete startup {{ startup.name }}?
    </p>
    <a href="{{ startup.get_absolute_url }}">
      Cancel
    </a>
    <button type="submit">Delete Startup</button>
  </form>
{% endblock %}

src/templates/startup/detail.html
{% extends parent_template|default:"startup/base.html" %}

{% block title %}
  {{ startup.name }}
{% endblock %}

{% block content %}
  <h2>{{ startup.name }}</h2>
  {% if perms.organizer.change_startup or perms.organizer.delete_startup %}
  <ul>
    {% if perms.organizer.change_startup %}
      <li>
        <a href="{{ startup.get_update_url }}">
          Update
        </a>
      </li>
    {% endif %}
    {% if perms.organizer.delete_startup %}
      <li>
        <a href="{{ startup.get_delete_url }}">
          Delete
        </a>
      </li>
    {% endif %}
  </ul>
  {% endif %}
  <dl>
    <dt>Date Founded</dt>
      <dd>{{ startup.founded_date|date:"F jS, Y" }}</dd>
    <dt>Website</dt>
      <dd>{{ startup.website|urlize }}</dd>
    <dt>Contact</dt>
      <dd>{{ startup.contact }}</dd>

    {% with tag_list=startup.tags.all %}
      <dt>Tag{{ tag_list|pluralize }}</dt>
        {% for tag in tag_list %}
          <dd><a href="{{ tag.get_absolute_url }}">
            {{ tag.name|title }}
          </a></dd>
        {% endfor %}
    {% endwith %}
  </dl>
  {{ startup.description|linebreaks }}
  <section>
    {% if perms.organizer.add_newslink %}
      <p>
        <a href="{{ startup.get_newslink_create_url }}">
          Add link to article
        </a>
      </p>
    {% endif %}
    <ul>
      {% for newslink in startup.newslink_set.all %}
        <li>
          <a href="{{ newslink.link }}">
            {{ newslink.title|title }}
          </a>
          {% if perms.organizer.change_newslink or perms.organizer.delete_newslink %}
            <ul>
              {% if perms.organizer.change_newslink %}
                <li>
                  <a href="{{ newslink.get_update_url }}">
                    Modify Link
                  </a>
                </li>
              {% endif %}
              {% if perms.organizer.delete_newslink %}
                <li>
                  <a href="{{ newslink.get_delete_url }}">
                    Delete Link
                  </a>
                </li>
              {% endif %}
            </ul>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  </section>
{% endblock %}

src/templates/startup/form.html
{% extends parent_template|default:"startup/base.html" %}

{% block title %}
  {{ block.super }} - {% if update %}Update{% else %}Create{% endif %} Startup
{% endblock %}

{% block content %}
  <form
      action="."
      method="post"
  >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
      {% if update %}Update{% else %}Create{% endif %} Startup
    </button>
  </form>
{% endblock %}

src/templates/startup/list.html
{% extends parent_template|default:"startup/base.html" %}

{% block title %}
  {{ block.super }} - Startups
{% endblock %}

{% block content %}
  <h2>Startup List</h2>
  {% if perms.organizer.add_startup %}
    <p>
      <a href="{% url 'startup_create' %}">
        Add Startup
      </a>
    </p>
  {% endif %}
  <ul>
    {% for startup in startup_list %}
      <li>
        <a href="{{ startup.get_absolute_url }}">
          {{ startup.name }}</a>
      </li>
    {% empty %}
      <li><em>No Startups Available</em></li>
    {% endfor %}
  </ul>
{% endblock %}