src/blog/urls.py
"""URL paths for Blog App"""
from django.urls import path

from .views import (
    PostArchiveMonth,
    PostArchiveYear,
    PostCreate,
    PostDelete,
    PostDetail,
    PostList,
    PostUpdate,
)

urlpatterns = [
    path("", PostList.as_view(), name="post_list"),
    path(
        "create/", PostCreate.as_view(), name="post_create"
    ),
    path(
        "<int:year>/",
        PostArchiveYear.as_view(),
        name="post_archive_year",
    ),
    path(
        "<int:year>/<int:month>/",
        PostArchiveMonth.as_view(),
        name="post_archive_month",
    ),
    path(
        "<int:year>/<int:month>/<str:slug>/",
        PostDetail.as_view(),
        name="post_detail",
    ),
    path(
        "<int:year>/<int:month>/<str:slug>/delete/",
        PostDelete.as_view(),
        name="post_delete",
    ),
    path(
        "<int:year>/<int:month>/<str:slug>/update/",
        PostUpdate.as_view(),
        name="post_update",
    ),
]

src/blog/models.py
"""Django data models for news

Django Model Documentation:
https://docs.djangoproject.com/en/2.2/topics/db/models/
https://docs.djangoproject.com/en/2.2/ref/models/options/
https://docs.djangoproject.com/en/2.2/internals/contributing/writing-code/coding-style/#model-style
Django Field Reference:
https://docs.djangoproject.com/en/2.2/ref/models/fields/
https://docs.djangoproject.com/en/2.2/ref/models/fields/#charfield
https://docs.djangoproject.com/en/2.2/ref/models/fields/#datefield
https://docs.djangoproject.com/en/2.2/ref/models/fields/#manytomanyfield
https://docs.djangoproject.com/en/2.2/ref/models/fields/#slugfield
https://docs.djangoproject.com/en/2.2/ref/models/fields/#textfield

"""
from datetime import date

from django.db.models import (
    CharField,
    DateField,
    ManyToManyField,
    Model,
    SlugField,
    TextField,
)
from django.urls import reverse

from organizer.models import Startup, Tag


class Post(Model):
    """Blog post; news article about startups"""

    title = CharField(max_length=63)
    slug = SlugField(
        max_length=63,
        help_text="A label for URL config",
        unique_for_month="pub_date",
    )
    text = TextField()
    pub_date = DateField(
        "date published", default=date.today
    )
    tags = ManyToManyField(Tag, related_name="blog_posts")
    startups = ManyToManyField(
        Startup, related_name="blog_posts"
    )

    class Meta:
        get_latest_by = "pub_date"
        ordering = ["-pub_date", "title"]
        verbose_name = "blog post"

    def __str__(self):
        date_string = self.pub_date.strftime("%Y-%m-%d")
        return f"{self.title} on {date_string}"

    def get_absolute_url(self):
        """Return URL to detail page of Post"""
        return reverse(
            "post_detail",
            kwargs={
                "year": self.pub_date.year,
                "month": self.pub_date.month,
                "slug": self.slug,
            },
        )

    def get_update_url(self):
        """Return URL to update page of Post"""
        return reverse(
            "post_update",
            kwargs={
                "year": self.pub_date.year,
                "month": self.pub_date.month,
                "slug": self.slug,
            },
        )

    def get_delete_url(self):
        """Return URL to delete page of Post"""
        return reverse(
            "post_delete",
            kwargs={
                "year": self.pub_date.year,
                "month": self.pub_date.month,
                "slug": self.slug,
            },
        )

    def short_text(self):
        """Generate short blurb based on text"""
        if len(self.text) > 20:
            short = " ".join(self.text.split()[:20])
            short += " ..."
        else:
            short = self.text
        return short

src/templates/post/confirm_delete.html
{% extends parent_template|default:"post/base.html" %}

{% block title %}
  {{ post.name }}: delete?
{% endblock %}

{% block content %}
  <form
      action="."
      method="post"
  >
    {% csrf_token %}
    <p>
      Are you sure you want to delete blog post {{ post.name }}?
    </p>
    <a href="{{ post.get_absolute_url }}">
      Cancel
    </a>
    <button type="submit">Delete Blog Post</button>
  </form>
{% endblock %}

src/templates/post/detail.html
{% extends parent_template|default:"post/base.html" %}

{% block title %}
  {{ block.super }} - {{ post.title|title }}
{% endblock %}

{% block content %}
  <article>
    <header>
      <h2>{{ post.title|title }}</h2>
      <p>
        Written on
        <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
          {{ post.pub_date|date:"l, F j, Y" }}
        </time>
      </p>
    </header>
    {{ post.text|linebreaks }}
    {% if perms.blog.change_post or perms.blog.delete_post %}
      <ul>
        {% if perms.blog.change_post %}
          <li>
            <a href="{{ post.get_update_url }}">
              Edit
            </a>
          </li>
        {% endif %}
        {% if perms.blog.delete_post %}
          <li>
            <a href="{{ post.get_delete_url }}">
              Delete
            </a>
          </li>
        {% endif %}
      </ul>
    {% endif %}
    {% if post.startups.all or post.tags.all %}
      <footer>
        {% with startup_list=post.startups.all %}
          {% if startup_list %}
            <section>
              <h3>Startup{{ startup_list|pluralize }}</h3>
              <ul>
                {% for startup in startup_list %}
                  <li><a href="{{ startup.get_absolute_url }}">
                    {{ startup.name }}
                  </a></li>
                {% endfor %}
              </ul>
            </section>
          {% endif %}
        {% endwith %}
        {% with tag_list=post.tags.all %}
          {% if tag_list %}
            <section>
              <h3>Tag{{ tag_list|pluralize }}</h3>
              <ul>
                {% for tag in tag_list %}
                  <li><a href="{{ tag.get_absolute_url }}">
                    {{ tag.name|title }}
                  </a></li>
                {% endfor %}
              </ul>
            </section>
          {% endif %}
        {% endwith %}
      </footer>
    {% endif %}
  </article>
{% endblock %}

src/templates/post/form.html
{% extends parent_template|default:"post/base.html" %}

{% block title %}
  {{ block.super }} - {% if update %}Update{% else %}Create{% endif %} Blog Post
{% endblock %}

{% block content %}
  <form
      action="."
      method="post"
  >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
      {% if update %}Update{% else %}Create{% endif %} Blog Post
    </button>
  </form>
{% endblock %}

src/templates/post/list.html
{% extends parent_template|default:"post/base.html" %}

{% block title %}
  {{ block.super }} - Blog
{% endblock %}

{% block content %}
  {% if perms.blog.add_post %}
    <p>
      <a href="{% url 'post_create' %}">
        Write Blog Post
      </a>
    <p>
  {% endif %}
  {% for post in post_list %}
    <article>
      <header>
        <h2>
          <a href="{{ post.get_absolute_url }}">
            {{ post.title|title }}</a>
        </h2>
        <p>
          Written on:
          <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
            {{ post.pub_date|date:"l, F j, Y" }}
          </time>
        </p>
      </header>
      <p>{{ post.text|truncatewords:20 }}</p>
      <p>
        <a href="{{ post.get_absolute_url }}">
          Read more…</a>
      </p>
    </article>
  {% empty %}
    <p><em>No Blog Posts Available</em></p>
  {% endfor %}
{% endblock %}

src/templates/post/post_archive_month.html
{% extends parent_template|default:"post/base.html" %}

{% block title %}
{{ block.super }} - {{ month|date:"F Y" }} Posts
{% endblock %}

{% block content %}
  <div class="row">
    <div class="eight columns">
      <div class="mobile">
        {% if perms.blog.add_post %}
          <a
            href="{% url 'post_create' %}"
            class="button button-primary"
          >
            Write Blog Post
          </a>
        {% endif %}
      </div>
      <h2>All Posts for {{ month|date:"F Y" }}</h2>
      {% for post in post_list %}
        <article class="list-item">
          <header>
            <h3>
              <a href="{{ post.get_absolute_url }}">
                {{ post.title|title }}
              </a>
            </h3>
            {% if perms.blog.change_post or perms.blog.delete_post %}
              <ul class="inline">
                {% if perms.blog.change_post %}
                  <li>
                    <a
                      href="{{ post.get_update_url }}"
                      class="button"
                    >
                      Edit Post
                    </a>
                  </li>
                {% endif %}
                {% if perms.blog.delete_post %}
                  <li>
                    <a
                      href="{{ post.get_delete_url }}"
                      class="button"
                    >
                      Delete Post
                    </a>
                  </li>
                {% endif %}
              </ul>
            {% endif %}
            <p>
              Written on:
              <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
                {{ post.pub_date|date:"l, F j, Y" }}
              </time>
            </p>
          </header>
          <p>{{ post.text|truncatewords:20 }}</p>
          <p class="read-more">
            <a href="{{ post.get_absolute_url }}">
                Read more…
            </a>
          </p>
        </article>
      {% endfor %}
    </div><!-- eight columns -->
    <div class="desktop four columns">
      {% if perms.blog.add_post %}
        <a
          href="{% url 'post_create' %}"
          class="button button-primary"
        >
          Write New Blog Post
        </a>
      {% endif %}
      <p>
        <a href="{% url 'post_archive_year' month|date:"Y" %}">
          All Posts from {{ month|date:"Y" }}
        </a>
      </p>
      <p>
        <a href="{% url 'post_list' %}">
          Latest Posts
        </a>
      </p>
    </div><!-- four columns -->
  </div><!-- row -->
  <div class="row">
    <div class="twelve columns">
      <ul class="pagination">
        {% if previous_month %}
          <li>
            <a href="{% url 'post_archive_month' previous_month|date:"Y" previous_month|date:"m" %}">
              ◀︎ Posts from {{ previous_month|date:"F Y" }}
            </a>
          </li>
        {% endif %}
        {% if next_month %}
          <li>
            <a href="{% url 'post_archive_month' next_month|date:"Y" next_month|date:"m" %}">
              Posts from {{ next_month|date:"F Y" }} ▶︎
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
{% endblock %}

src/templates/post/post_archive_year.html
{% extends parent_template|default:"post/base.html" %}

{% block title %}
{{ block.super }} - {{ year|date:"Y" }} Posts
{% endblock %}

{% block content %}
  <div class="row">
    <div class="eight columns">
      <div class="mobile">
        {% if perms.blog.add_post %}
          <a
            href="{% url 'post_create' %}"
            class="button button-primary"
          >
            Write Blog Post
          </a>
        {% endif %}
      </div>
      <h2>All Posts for {{ year|date:"Y" }}</h2>
      {% for post in post_list %}
        <article class="list-item">
          <header>
            <h3>
              <a href="{{ post.get_absolute_url }}">
                {{ post.title|title }}
              </a>
            </h3>
            {% if perms.blog.change_post or perms.blog.delete_post %}
              <ul class="inline">
                {% if perms.blog.change_post %}
                  <li>
                    <a
                      href="{{ post.get_update_url }}"
                      class="button"
                    >
                      Edit Post
                    </a>
                  </li>
                {% endif %}
                {% if perms.blog.delete_post %}
                  <li>
                    <a
                      href="{{ post.get_delete_url }}"
                      class="button"
                    >
                      Delete Post
                    </a>
                  </li>
                {% endif %}
              </ul>
            {% endif %}
            <p>
              Written on:
              <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
                {{ post.pub_date|date:"l, F j, Y" }}
              </time>
            </p>
          </header>
          <p>{{ post.text|truncatewords:20 }}</p>
          <p class="read-more">
            <a href="{{ post.get_absolute_url }}">
                Read more…
            </a>
          <p>
        </article>
      {% endfor %}
    </div>
    <div class="desktop four columns">
      {% if perms.blog.add_post %}
        <a
          href="{% url 'post_create' %}"
          class="button button-primary"
        >
          Write Blog Post
        </a>
      {% endif %}
      <h3>Archives by Month</h3>
      <ul>
        {% for m in date_list %}
          <li>
            <a href="{% url 'post_archive_month' m|date:"Y" m|date:"n" %}">
              {{ m|date:"F Y" }}
            </a>
          </li>
        {% endfor %}
      </ul>
      <p>
        <a href="{% url 'post_list' %}">
          Latest Posts
        </a>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns">
      <ul class="pagination">
        {% if previous_year %}
          <li>
            <a href="{% url 'post_archive_year' previous_year|date:"Y" %}">
              ❮ Posts from {{ previous_year|date:"Y" }}
            </a>
          </li>
        {% endif %}
        {% if next_year %}
          <li>
            <a href="{% url 'post_archive_year' next_year|date:"Y" %}">
              Posts from {{ next_year|date:"Y" }} ❯
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
{% endblock %}